[package]
name = "hovercraft"
version = "0.1.0"
edition = "2018"
default-run = "hovercraft"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
chrono = { version = "0.4", features = ["serde"] }
gl = "0.14.0"
rand = "0.6.5"
sdl2 = { version = "0.34.5", features = ["ttf", "image", "gfx"] }
