[package]
name = "hovercraft"
version = "0.1.0"
edition = "2021"
default-run = "astar"

[profile.dev.package."*"]
opt-level = 2

[dependencies]
anyhow = "1.0.44"
chrono = { version = "0.4", features = ["serde"] }
rand = "0.8.5"
